project_id = "nbugpbakfkyvvjzgfjmw"

[functions.send-notification]
verify_jwt = true

[functions.csv-intelligent-import]
verify_jwt = false

[functions.ai-fraud-detection]
verify_jwt = false

[functions.blog-ai-generator]
verify_jwt = false

[functions.blog-auto-publish]
verify_jwt = false

[functions.blog-image-generator]
verify_jwt = true

[functions.generate-local-seo-v3]
verify_jwt = false

[functions.geocode-repairers]
verify_jwt = false

[functions.batch-generate-local-seo]
verify_jwt = false

[functions.generate-repairer-seo-page]
verify_jwt = false

[functions.blog-schedules]
verify_jwt = false
