project_id = "nbugpbakfkyvvjzgfjmw"

[functions.send-notification]
verify_jwt = true

[functions.ai-fraud-detection]
verify_jwt = false

[functions.blog-ai-generator]
verify_jwt = false

[functions.blog-auto-publish]
verify_jwt = false

[functions.blog-image-generator]
verify_jwt = true

[functions.blog-update-images]
verify_jwt = false

[functions.generate-repairer-seo-page]
verify_jwt = false

[functions.blog-schedules]
verify_jwt = false
