project_id = "nbugpbakfkyvvjzgfjmw"

[functions.scrape-repairers]
verify_jwt = false

[functions.stop-scraping]
verify_jwt = false

[functions.validate-scraping]
verify_jwt = false

[functions.blog-scheduler-cron]
verify_jwt = false

[functions.send-notification]
verify_jwt = true

[functions.ai-fraud-detection]
verify_jwt = false

[functions.ai-content-helper]
verify_jwt = true

[functions.blog-ai-generator]
verify_jwt = false

[functions.blog-auto-publish]
verify_jwt = false

[functions.blog-image-generator]
verify_jwt = true

[functions.blog-update-images]
verify_jwt = true

[functions.generate-repairer-seo-page]
verify_jwt = false

[functions.blog-schedules]
verify_jwt = false

[functions.blog-ai-moderation]
verify_jwt = true
